### ISSUE TITLE
Allow doc comments

### ISSUE THREAD

**Issue by Chadehoc** [math4tots/rust-primitive_enum#1]
It would be nice to be able do add a doc comment to types defined by `primitive_enum!`. Naively adding a `/// my doc` or `#[doc = "my doc"]` above the line does not work.

**Comment by math4tots** [comment]
Heh, I'm at almost 2 years late at this point, but this feature has been added as of version 1.1.0, commit [523961e](https://github.com/math4tots/rust-primitive_enum/commit/523961ead0e48109c823ea9aa45a8d1e0e98f200), released today.
