### ISSUE TITLE
Freeze of rust compiler?

### ISSUE THREAD

**Issue by xxshady** [math4tots/rust-primitive_enum#2]
![изображение](https://user-images.githubusercontent.com/54737754/220228756-17ec9593-9710-4ffe-93c5-652f56a2d3bb.png)

**Comment by xxshady** [comment]
<img src="https://user-images.githubusercontent.com/54737754/220229187-150ce65d-446f-4069-b669-ecf7f38493a0.gif" alt="awkward-umm-what" width="100px">

**Comment by xxshady** [comment]
Seems like because of the way how this crate works it hangs the rust compiler with such input:
```rust
primitive_enum! { MarkerType u32 ;
    Markercone = 0,
    Markercylinder = 1,
    Markerarrow = 2,
    Markerarrowflat = 3,
    Markerflag = 4,
    Markerringflag = 5,
    Markerring = 6,
    Markerplane = 7,
    Markerbikelogo1 = 8,
    Markerbikelogo2 = 9,
    Markernum0 = 10,
    Markernum1 = 11,
    Markernum2 = 12,
    Markernum3 = 13,
    Markernum4 = 14,
    Markernum5 = 15,
    Markernum6 = 16,
    Markernum7 = 17,
    Markernum8 = 18,
    Markernum9 = 19,
    Markerchevron1 = 20,
    Markerchevron2 = 21,
    Markerchevron3 = 22,
    Markerringflat = 23,
    Markerlap = 24,
    Markerhalo = 25,
    Markerhalopoint = 26,
    Markerhalorotate = 27,
    Markersphere = 28,
    Markermoney = 29,
    Markerlines = 30,
    Markerbeast = 31,
    Markerquestionmark = 32,
    Markertransformplane = 33,
    Markertransformhelicopter = 34,
    Markertransformboat = 35,
    Markertransformcar = 36,
    Markertransformbike = 37,
    Markertransformpushbike = 38,
    Markertransformtruck = 39,
    Markertransformparachute = 40,
    Markertransformthruster = 41,
    Markerwarp = 42,
    Markerboxes = 43,
    Markerpitlane = 44,
}
```

**Comment by math4tots** [comment]
@xxshady Heh yea, it's kind of a limitation of declarative macros and not having eager evaluation.

Tbh It's been a while since I've touched Rust code, but I'll look into implementing this as a procedural macro instead. That should make this sort of thing actually work well

**Comment by math4tots** [comment]
@xxshady Done!

As of version 1.1.0, commit [523961e](https://github.com/math4tots/rust-primitive_enum/commit/523961ead0e48109c823ea9aa45a8d1e0e98f200), this create has been rewritten as a proc-macro, so the generated code should be saner and much faster to run now. I hope you don't mind I added your paste as a sample test case.

Let me know if it works for you now and I'll close this ticket.

**Comment by xxshady** [comment]
Seems like `pub` modifier for enum is missing in proc macro?

![изображение](https://user-images.githubusercontent.com/54737754/233860683-d47a12c0-afcd-4686-8ecd-a585ee0d0793.png)

**Comment by xxshady** [comment]
> I hope you don't mind I added your paste as a sample test case

Yep, I don't mind

**Comment by math4tots** [comment]
Ahhh shoot, let me fix that

**Comment by math4tots** [comment]
Ok, should be fixed now, starting 1.1.1

**Comment by xxshady** [comment]
Testing it

**Comment by xxshady** [comment]
![изображение](https://user-images.githubusercontent.com/54737754/233861233-f704f7ed-163e-4c16-9e79-eea45f82808f.png)

Thats a win

**Comment by xxshady** [comment]
Thank you for the fix ❤️

**Comment by math4tots** [comment]
Cool~, Ima gonna close the ticket then,

@xxshady thanks for reporting the issue and seeing it through 🤓
